[package]
name = "package"
version = "0.1.1"
description = "Packages the ptex binary."
authors = [
    "John Sirois <john.sirois@gmail.com>",
]
edition = "2021"
publish = false

[build-dependencies]
ptex = { path="..", artifact="bin" }
sha2 = "0.10"

[dependencies]
proc-exit = "2.0"